### ISSUE TITLE
Removal of the OH 1.x Compatibility Layer in OH3

### ISSUE THREAD

**Issue by ModuloFS** [docbender/openHAB-SimpleBinary#3]
Hello docbender,

i've read a posting in the openHAB-Community forum about removing the OH 1.X compatibility Layer in openHAB3. (https://community.openhab.org/t/removal-of-the-oh-1-x-compatibility-layer/67553) Do you still maintaining your SimpleBinary-Binding in the future? So are you planing to move your Binding to the new architecture if it wont work with future versions of openHAB?

**Comment by docbender** [comment]
Hi,
my answer is yes. If in OH3 will be OH1 bindings deprecated and I have spare time, I'll plan to rewrite it. But not in close future. I'll wait for final decision and to see how API3.0 will look. Ideally at least till OH3 alpha or rather beta will be released. If it will contain some essential functions (scheduler, jython scripting, full featured textplain configuration), motivation will be greater. Cos OH2 for me is not big step forward and my system still runs on OH1.8
