### ISSUE TITLE
Problems with openHAB 2.5

### ISSUE THREAD

**Issue by ModuloFS** [docbender/openHAB-SimpleBinary#4]
Hello docbender,

i just installed the new openHAB-version 2.5 and no i get this error at startup of the OH system:

> 2019-12-21 15:19:10.187 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.simplebinary-1.10.0-SNAPSHOT.jar
> 
> org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.simplebinary [19]
> 
>   Unresolved requirement: Import-Package: gnu.io
> 
> 	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
> 
> 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
> 
> 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
> 
> 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
> 
> 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.4]
> 
> 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.4]
> 
> 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
> 
> 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]

Is your binding working at your setup with OH 2.5? Do you have any suggestions where my problem is?

**Comment by docbender** [comment]
No I did not test it. But it looks like serial communication dependacy is broken. Try to install serial depedancy in OH console:
<code>feature:install openhab-transport-serial</code>

**Comment by ModuloFS** [comment]
Ok, your solution fixed the Problem! Thank you very much for your support!!
