### ISSUE TITLE
Rollershutter datetype changed

### ISSUE THREAD

**Issue by ModuloFS** [docbender/openHAB-SimpleBinary#7]
Hello Vita,

i have just moved my system to OH3. First of all, thank you for your great work to upgrade your binding to OH3!! You have to add your binding description to the official website! I think this binding is the most important binding for selfmade wired smart home devices!!!

I have noticed, you changed the datetype of the Rollershutter command on the bus. In the legacy version of your binding you sent two bytes with the command ( UP, DOWN, STOP, MOVE) and the Percentage value. Now you are only send one byte with the command.

Is there a special reason why you have done this?

Because i think your first solution to have the additional possibility to send a desired position in percent for the rollershutter instead of only move, stop, up, down was better.

Best Regards!

Flo

**Comment by docbender** [comment]
Hi,

rollershutter data should be word datatype.  In readme it is wrongly described. In OH GUI it is correct. Binding accepts UP, DOWN, STOP and PERCENT commands. But I have to test this behavior. I just looked into source and something  looks bad to me.

To add binding to OH website. I add it if there will be OH marketplace. Till then direct contributing into OH3 repository is a long shot.

**Comment by docbender** [comment]
I corrected items address definition and bindings readme. Now roller shutter data are defined as word in target device.

**Comment by ModuloFS** [comment]
Hi,

i just want to try it out but i run in some trouble. openHAB wants to start the binding but, cannot do it and gives me the follwoing log-entry:
`2021-06-18 19:41:46.482 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.simplebinary-3.1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.simplebinary [254]
  Unresolved requirement: Import-Package: javax.measure; version="[2.1.0,3.0.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]`

Do i have to install OH 3.1 for this? It seems the binding needs some javax.measure import.

I have a second topic. Is it right, you put the command (UP, DOWN, MOVE, STOP) into the low byte and the position in the high byte. But in the OH 1.8 version of the binding it was the other way around i think?

**Comment by docbender** [comment]
Latest 3.1.0 release need at least OH 3.1 M5 version. There are breaking changes since this version. Final OH3.1 version should be released within 14 days. 

I will look at byte order of rollershutter item. I will unify it with previous version.



18. 6. 2021 20:02, 20:02, ModuloFS ***@***.***> napsal/a:

**Comment by docbender** [comment]
Command byte order for rollershutter is fixed. 
This binding has been converted by simatic binding, which has it backwards :-(

**Comment by ModuloFS** [comment]
Just tested the new version and its working fine! Thank you!
