### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by dds90** [docbender/openHAB-SimpleBinary#8]
You can find attached some debug log files: [1](https://github.com/docbender/openHAB-SimpleBinary/files/7729861/Start.4.devices.-.delay.txt) - [2](https://github.com/docbender/openHAB-SimpleBinary/files/7729862/4.devices.with.previous.config.txt) - [3](https://github.com/docbender/openHAB-SimpleBinary/files/7729863/4.devices.with.new.example.fw.txt) - [4](https://github.com/docbender/openHAB-SimpleBinary/files/7729864/Only.one.device.with.new.example.fw.txt)

**Comment by docbender** [comment]
First what I see is that binding ask device 3 if device has data:
```
2021-12-16 18:46:09.637 [DEBUG] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - Sending data to device 3 with length 4 bytes
2021-12-16 18:46:09.639 [DEBUG] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - data: [0x3 0xD0 0x1 0x0]
```
But answer is from device 1:
```
2021-12-16 18:46:11.233 [DEBUG] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - received: [0x1 0xE7 0x0 0x43]
2021-12-16 18:46:11.237 [ERROR] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - Address not valid: received/sent=1/3
```
Do not call _sendWantAllData()_. Only call _setSave(...)_ or _setNewData_ as in examples. The data is marked to be sent when binding ask for them.

**Comment by dds90** [comment]
Yes, There are errors there because I was trying to force the data update directly from the slave.
If it is not possible in any way, I leave this attempt.

In the other 3 files there are other errors

**Comment by docbender** [comment]
Continuing from the end (log 4). Warnings in log file should be better formatted debug messages. Rest of data will arrive and packet is accepted:

> 2021-12-16 18:21:11.666 [DEBUG] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - received: [0x2 0xDC 0x1 0x0 0xE5 0x2] 
> 2021-12-16 18:21:11.667 [DEBUG] [ernal.core.SimpleBinaryGenericDevice] - Port /dev/ttyUSB0 - Reading input buffer, lenght=6 bytes. Thread=660 
> 2021-12-16 18:21:11.668 [WARN ] [ernal.core.SimpleBinaryGenericDevice] - Port /dev/ttyUSB0 - Cannot decompile incoming data 
> 2021-12-16 18:21:11.691 [DEBUG] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - received: [0x0 0x0 0x70] 
> 2021-12-16 18:21:11.692 [DEBUG] [ernal.core.SimpleBinaryGenericDevice] - Port /dev/ttyUSB0 - Reading input buffer, lenght=9 bytes. Thread=660 
> 2021-12-16 18:21:11.694 [DEBUG] [ernal.core.SimpleBinaryGenericDevice] - Port /dev/ttyUSB0 - Device 2 Incoming data - channel:simplebinary:generic_device:sbrs485:counters:UpTime/state:741

New issue #9 is created for this.

**Comment by docbender** [comment]
I have no quick solution. From your log file 3 I see sometimes in 4 device configuration received data are discarded. One two devices are fine, four not. I'll rewrite communication side, which was made for OH1.
You can set the read mode as ONSCAN before the fix is available.

**Comment by docbender** [comment]
I released [new version](https://github.com/docbender/openHAB-SimpleBinary/releases/download/3.2.0-beta.7/org.openhab.binding.simplebinary-3.2.0.jar) . There is better device write/read isolation handling. You can test it and give feedback if the behavior of the binding is better now with your system configuration.

**Comment by dds90** [comment]
Hi Vita,
Thank you very much for your work and for your support. I've just load the new binding version. I let it run for some time. I'll update you as soon as I see something!

**Comment by dds90** [comment]
Hi Vita,
Unfortunately this afternoon the system crashed again.
It seems that now the problem is on the CRC. Some idea?
You can find attached the debug log files: [2022-01-13_Stop&Restart.txt](https://github.com/docbender/openHAB-SimpleBinary/files/7866273/2022-01-13_Stop.Restart.txt)

**Comment by docbender** [comment]
"
As I can see from log, there is a problem in the data transfer. Data 0x2 0xE
2 0x0 0xFF are received. Message CRC is 0xFF and it should be 0xBF. One bit 
is wrong. My recommendation is to reduce bit rate.
""

""
 
""

"" "

**Comment by dds90** [comment]
Thanks again for your patience.
Beyond the errors due to the CRC, sometimes it happens that the communication stops. 
You can find attached the debug log files:
-[2022-01-19_Stop.txt](https://github.com/docbender/openHAB-SimpleBinary/files/7921211/2022-01-19_Stop.txt)
-[2022-01-23_Stop.txt](https://github.com/docbender/openHAB-SimpleBinary/files/7921212/2022-01-23_Stop.txt)

**Comment by docbender** [comment]
I have already noticed this problem and at least I catch it in source code. I have now also prepared [a release](https://github.com/docbender/openHAB-SimpleBinary/releases/download/3.2.0-beta.8/org.openhab.binding.simplebinary-3.2.0.jar).
