### ISSUE TITLE
If packet arrives split log is filled with warnings

### ISSUE THREAD

**Issue by docbender** [docbender/openHAB-SimpleBinary#9]
In some cases (maybe device is slow or controller to fast) data is split. Unnecessary warning level message is generated:
> 18:21:11.666 [DEBUG] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - received: [0x2 0xDC 0x1 0x0 0xE5 0x2]
> 18:21:11.667 [DEBUG] [ernal.core.SimpleBinaryGenericDevice] - Port /dev/ttyUSB0 - Reading input buffer, lenght=6 bytes. Thread=660
> 18:21:11.668 [WARN ] [ernal.core.SimpleBinaryGenericDevice] - Port /dev/ttyUSB0 - Cannot decompile incoming data
> 18:21:11.691 [DEBUG] [inary.internal.core.SimpleBinaryUART] - Port /dev/ttyUSB0 - received: [0x0 0x0 0x70]

**Comment by ModuloFS** [comment]
Hello Vita,

i do not know the timing of the processing of the protocol but maybe the timing / framing principle of modbus RTU would be good for your bus protocol? Take a look at https://www.modbus.org/docs/Modbus_over_serial_line_V1_02.pdf chapter 2.5.1.1 MODBUS Message RTU Framing
